#!/bin/sh
CUR=`dirname $0`
CUR=`pwd $CUR`

if [[ $# -lt 1 ]]; then
    echo "Usage: $0	<url>	[output-file]"
    exit 0
fi
url=$1
if [[ ! -z "$2" ]]; then
    output="$2.%(ext)s"
fi

PROXY_URL="socks5://181.222.15.6:15634"
PROXY_URL="socks4://171.217.127.112:1080"
PROXY_URL="socks5://116.196.100.186:9000"
PROXY_URL="socks5://172.31.47.87:8388"
PROXY_URL="socks5://180.76.105.251:8388"
SOCKET_TIMEOUT=120
command="$CUR/youtube-dl --write-sub --extract-audio --continue --audio-format wav --audio-quality 0 --all-subs --socket-timeout ${SOCKET_TIMEOUT} --proxy ${PROXY_URL} ${url}"
if [[ -z "$output" ]]; then
    $command
else
    $command -o ${output}
fi
